version: '3.1'

services:
  wordpress:
    image: wordpress:latest
    volumes:
      - ./:/var/www/html
      - ./config-wp.like-minded.dk.php:/usr/share/wordpress/config-wp.like-minded.dk.php:ro
    environment:
      WORDPRESS_DB_HOST: 127.0.0.1
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 12345678
      WORDPRESS_DB_NAME: wordpress

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/ssl/certs:ro
    depends_on:
      - wordpress
volumes:
  wordpress_data:
  db_data:
